### ISSUE TITLE
Docs Do Not Match Code Comments

### ISSUE THREAD

**Issue by pirouet** [TypedProject/tsed#629]
## Information

- **Version:** Latest (v5)
- **Type:** 

## Description
There appears to be some confusion - at least from my side - about what the Docs say and what the code says. Following the documentation, it states to use the mount object on the ServerSettings, but within code this is showing as deprecated and to use other bits instead. Similliarly using ServerLoad.boostrap, etc.

Is there a plan to update the docs to match this or is this prep work for v6?  

I love the approach taken by TsEd but it's just a bit confusing in my opinion. Any advise would be beneficial, thanks

**Comment by Romakita** [comment]
I'm sorry about confusing doc. Can you give the link/page where the doc is confusing exactly. I try to fix it ASAP?
My apologize again :)
Romain

**Comment by pirouet** [comment]
No problem at all. It's let about the Docs are confusing but it's the combination of following the docs and then seeing the code

For example, http://tsed.io/getting-started.html#create-your-express-server states using @ServerSettings (which seems fine) but when implementing this, my IDE complains that the "mount" and "componentsScan" are deprecated and to use  alternative options such as addControllers and to use ServerLoader.bootstrap

**Comment by Romakita** [comment]
haaa ok. I deprecated mount and componentScan by error. Only method on ServerLoader (mount and componentScan) are deprecated. 

I'll revert this.

mount and componentScan (with ServerSettings decorator) are currently the right way to register controller and provider. In haven't other satisfying way or plan to configure Controller and Provider.

Thanks a lot for your feedback ;)
If you found other confusing stuff in our documentation, tel me :)

Romain

**Comment by chiqui3d** [comment]
I like the way you have it, but only as information another way would be like Symfony or even TypeORM with a configuration file:

ormconfig.yml
```yml
default:
  name: default
  type: mysql
  database:  test
  host: localhost
  port: 3306
  username: root
  password: pass__123
  entities: [ dist/Entity/**/*.js ]
  subscribers: [ dist/Subscriber/**/*.js ]
  migrations: [ dist/Migration/**/*.js ]
  cli:
    migrationsDir: src/Migration
    entitiesDir: src/Entity
    subscribersDir: src/Subscriber
  synchronize: true
  logging: false
```

The problem with this is that someone might need dynamic options, but it's very unlikely, so if it's true that you need to do it inside the app
